from django.conf.urls import url
from django.contrib.auth.views import login, logout
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index/$', views.index, name='index'),
    url(r'^/lembur/(?P<ket>[a-zA-Z0-9_]*)/$', views.lembur, name='lembur'),
    url(r'^/ajukanlembur/$', views.ajukanlembur, name='ajukanlembur'),
    url(r'^/ajukanlemburmanager/$', views.ajukanlemburmanager, name='ajukanlemburmanager'),
    url(r'^/lihatlembur/$', views.lihatlembur, name='lihatlembur'),
    url(r'^/ubahlembur/$', views.ubahlembur, name='ubahlembur'),
    url(r'^/hapuslembur/$', views.hapuslembur, name='hapuslembur'),
    url(r'^/caripegawai/$', views.caripegawai, name='caripegawai'),
    url(r'^/cariuser/$', views.cariuser, name='cariuser'),
    url(r'^/cekabsen/$', views.cekabsen, name='cekabsen'),
    url(r'^/formharikerja/(?P<id>[0-9]+)/$', views.formharikerja, name='formharikerja'),
    url(r'^/formharilibur/(?P<id>[0-9]+)/$', views.formharilibur, name='formharilibur'),
    url(r'^/pdfharikerja/(?P<id>[0-9]+)/$', views.pdfharikerja, name='pdfharikerja'),
    url(r'^/pdfharilibur/(?P<id>[0-9]+)/$', views.pdfharilibur, name='pdfharilibur'),
    url(r'^/cariperiode/$', views.cariperiode, name='cariperiode'),
    url(r'^/pdflaporanperiode/$', views.pdflaporanperiode, name='pdflaporanperiode'),
    url(r'^/cariperminggu/$', views.cariperminggu, name='cariperminggu'),
    url(r'^/pdflaporanperminggu/$', views.pdflaporanperminggu, name='pdflaporanperminggu'),
    url(r'^/mdviewpegawai/$', views.mdviewpegawai, name='mdviewpegawai'),
    url(r'^/mdcreatepegawai/$', views.mdcreatepegawai, name='mdcreatepegawai'),
    url(r'^/mdeditpegawai/$', views.mdeditpegawai, name='mdeditpegawai'),
    url(r'^/mddeletepegawai/$', views.mddeletepegawai, name='mddeletepegawai'),
    url(r'^/mdviewjabatan/$', views.mdviewjabatan, name='mdviewjabatan'),
    url(r'^/mdcreatejabatan/$', views.mdcreatejabatan, name='mdcreatejabatan'),
    url(r'^/mdeditjabatan/$', views.mdeditjabatan, name='mdeditjabatan'),
    url(r'^/mddeletejabatan/$', views.mddeletejabatan, name='mddeletejabatan'),
    url(r'^/mdviewjenislembur/$', views.mdviewjenislembur, name='mdviewjenislembur'),
    url(r'^/mdcreatejenislembur/$', views.mdcreatejenislembur, name='mdcreatejenislembur'),
    url(r'^/mdeditjenislembur/$', views.mdeditjenislembur, name='mdeditjenislembur'),
    url(r'^/mddeletejenislembur/$', views.mddeletejenislembur, name='mddeletejenislembur'),
    url(r'^/mdviewkomponenlembur/$', views.mdviewkomponenlembur, name='mdviewkomponenlembur'),
    url(r'^/mdcreatekomponenlembur/$', views.mdcreatekomponenlembur, name='mdcreatekomponenlembur'),
    url(r'^/mdeditkomponenlembur/$', views.mdeditkomponenlembur, name='mdeditkomponenlembur'),
    url(r'^/mddeletekomponenlembur/$', views.mddeletekomponenlembur, name='mddeletekomponenlembur'),
    url(r'^/mdviewlembur/$', views.mdviewlembur, name='mdviewlembur'),
    url(r'^/mdcreatelembur/$', views.mdcreatelembur, name='mdcreatelembur'),
    url(r'^/mdeditlembur/$', views.mdeditlembur, name='mdeditlembur'),
    url(r'^/mddeletelembur/$', views.mddeletelembur, name='mddeletelembur'),
    url(r'^/mdviewstatuslembur/$', views.mdviewstatuslembur, name='mdviewstatuslembur'),
    url(r'^/mdcreatestatuslembur/$', views.mdcreatestatuslembur, name='mdcreatestatuslembur'),
    url(r'^/mdeditstatuslembur/$', views.mdeditstatuslembur, name='mdeditstatuslembur'),
    url(r'^/mddeletestatuslembur/$', views.mddeletestatuslembur, name='mddeletestatuslembur'),
    url(r'^/mdviewunitkerja/$', views.mdviewunitkerja, name='mdviewunitkerja'),
    url(r'^/mdcreateunitkerja/$', views.mdcreateunitkerja, name='mdcreateunitkerja'),
    url(r'^/mdeditunitkerja/$', views.mdeditunitkerja, name='mdeditunitkerja'),
    url(r'^/mddeleteunitkerja/$', views.mddeleteunitkerja, name='mddeleteunitkerja'),
    url(r'^/mdviewpermissionlembur/$', views.mdviewpermissionlembur, name='mdviewpermissionlembur'),
    url(r'^/mdcreatepermissionlembur/$', views.mdcreatepermissionlembur, name='mdcreatepermissionlembur'),
    url(r'^/mdeditpermissionlembur/$', views.mdeditpermissionlembur, name='mdeditpermissionlembur'),
    url(r'^/mddeletepermissionlembur/$', views.mddeletepermissionlembur, name='mddeletepermissionlembur')
]
